### ISSUE TITLE
[RFC] To choose userId vs userName for featureFlag-UserMapping table.

### ISSUE THREAD

**Issue by vikhyat187** [Real-Dev-Squad/feature-flag-backend#6]
`Context`: This thing is related to `feature flag service`, the ER diagram can be referred to here https://github.com/Real-Dev-Squad/feature-flag-backend/blob/develop/ER%20diagram.jpg. 
We have 3 tables(entities) being used
- Users (existing in Firestore)
- Feature Flag table **(To be created)**
- Feature flag User mapping table **(To be created)**

Now for the table `FeatureFlag-Usermapping` table, we need to decide which field to go with `userId` vs `userName` for storing the data like 
| FlagId |  userId / userName |
| ---------| ----------|
| flag1 | DT4hSCaSxlEgOjZdWLx7 / vikhyat |

- By using `username` it will be intuitive to understand which users are enabled for a feature flag
- Flag1, Vikhyat -> ENABLED
- In the case of `userId` we need to query the `userId` generated by Firestore to fetch the user details.

## Open questions
- Do we have an index on `userName` in Firestore, if yes we can use `username` in the `FeatureFlag-User mapping` table
- Do we have any document to refer for which all attributes have an index created on

What are your thoughts on this, which attribute to choose `userId` or `userName` for `FeatureFlag-user mapping ` table.

**Comment by dev-gv** [comment]
Hey @vikhyat187 some thoughts on this
- guessing username is unique?
- why is user id a bad option? considering ids generally exists for this. 
- Do you want to identify the user with the mapping? what is driving this requirement?

**Comment by vikhyat187** [comment]
Hello @dev-gv,
- Yes the username is unique.
- I was thinking of a username, instead of userId, as it would be easier from a human perspective to identify the feature flag for a user, but realised that we don't usually see the data in the database.

**Comment by ankushdharkar** [comment]
Our usernames are unique, but they are subject to change in future (we want "good" usernames to belong to currently active users).
