### ISSUE TITLE
[Design Doc] Rate Limiting AWS Lambdas for Feature Flags

### ISSUE THREAD

**Issue by shubham-y** [Real-Dev-Squad/feature-flag-backend#73]
## Problem
Limit the number of Lambda invocations to a maximum of 500 per API to control usage and prevent abuse.

### Approach 1: Using API Usage Plans & API Keys in AWS API Gateway

**Description:** In this approach, we will utilize AWS API Gateway's API Usage plans and API keys to enforce rate limits on Lambda invocations.

1. **API Usage Plan and API Key Setup:**
   - Create an API Usage plan for each API endpoint.
   - Configure the usage plan with a maximum limit of 500 requests per month.
   - Generate an API key for each usage plan.

2. **`website-backend` Proxy:**
   - Develop an endpoint in the `website-backend` for each Lambda.
   - Store the generated API keys in a configuration file.
   - Pass the appropriate API key in the `x-api-key` header when making requests to API Gateway endpoints.

**Advantages:**
   - Customizable and updatable rate limits for each API endpoint.
   - Future automation potential using AWS CDK for limit updates and usage reporting.
   - Flexibility to extend backend functionality, such as Firestore access and role-based authentication.

**Disadvantages:**
   - Single point of failure (backend) could compromise Lambda scalability.
   - Potential lack of separation of concerns if business logic is distributed between backend and Lambdas.
  
**References:**
   - https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html

### Approach 2: Using Lambda Authorizer and AWS DynamoDB

**Description:** This approach involves utilizing AWS Lambda Authorizer and DynamoDB to enforce rate limits on Lambda invocations.

1. **Lambda Authorizer Implementation:**
   - Implement a Lambda Authorizer function.
   - Configure API Gateway to invoke the authorizer before any Lambda invocation.
   - The authorizer will return an IAM policy based on the request's authentication and authorization.

2. **DynamoDB Table for Mapping and Limits:**
   - Create a DynamoDB table to store mappings between endpoints and their invocation limits.
   - Query this table within the Lambda function to determine the current usage and update limits.

3. **Rate Limit Check in Lambda:**
   - The Lambda function queries the DynamoDB table to check the current usage against the limit.
   - If the limit is exceeded, return an IAM policy with `Effect` set to `Deny`; otherwise, set it to `Allow`.

**Advantages:**
   - Scalability and separation of concerns are maintained as there's no proxy service.
   - Easy integration of authorization using Lambda Authorizer with JWT token roles.

**Disadvantages:**
   - Possible timeout issues if additional logic is added to a single Lambda function(Lambda Authorizer).
   - Additional costs incurred due to DynamoDB read and write operations for every request.
   - Automation of limit updates might introduce complexity.
   
**References:**
   - https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

**Comment by vikhyat187** [comment]
Closing this as we implemented it
